//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLogic.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class MemberMaster
    {
        public int MemberId { get; set; }
        public string MemberImage { get; set; }
        public string MemberName { get; set; }
        public bool Gender { get; set; }
        public string Address { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
        public Nullable<decimal> PhoneHome1 { get; set; }
        public Nullable<decimal> PhoneWork1 { get; set; }
        public string Email { get; set; }
        public Nullable<int> Membershiptypeid { get; set; }
        public string Note { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public Nullable<int> Updated { get; set; }
    }
}
